theme: jekyll-theme-cayman
include:
 - "_images"
 - "../../../_"
 
 https://eitco.github.io/arveo/antora_website/_/js/vendor/highlight.js
 https://eitco.github.io/arveo/antora_website/_/js/site.js
 https://eitco.github.io/arveo/antora_website/arveo-docu/feature-ECR-1330-redesign-ascii-documentation/arveo-developer/_images/arveo_infografik_dokument-lebenszyklus-gruen.png