:icons: font

The `eql-jooq` module provides an EQL based `SearchService` that can be used with https://www.jooq.org/[JOOQ].
Basically, the SearchServices uses a JOOQ `DSLContext` to provide query results containing `Record` items.

The `JooqSearchService` can be instantiated using a builder pattern as shown in the following example:

.Instantiation of a JooqSearchService
[source, java, indent=0]
----
include::../../../../jooq/src/test/java/de/eitco/commons/query/language/jooq/test/JooqSearchServiceSqlTest.java[tag=jooq-search-service]
----
<1> The list of fields to select or the asterisk.
<2> The table to use for the queries. Could be a single table or a join.
<3> A configured DSLContext instance

The second type parameter (`Object`) of the search service results from the input type of the visitor implementation
used to transform an EQL quer to a JOOQ query and is not significant for the usage of the SearchService. Instead of
a generic table (as used in the example), a table generated by the JOOQ code generator can be used, too.

Once the service was instantiated, it can be used to perform queries as shown below:

.Usage of the search service
[source,java,indent=0]
----
include::../../../../jooq/src/test/java/de/eitco/commons/query/language/jooq/test/JooqSearchServiceSqlTest.java[tag=jooq-service-usage]
----

The search service provides the same fluent API as any EQL SearchService. The EQL expression formulated using the API
will be translated to a JOOQ query.