
As one can see, the interface `SearchService` has a lot of default methods but only on abstract method:

.The method `search()`
[source,java]
----
include::../../../../api/src/test/java/de/eitco/commons/query/language/api/test/sample/Fluent.java[tag=low-level]
----

The method is given a `SearchRequest` and retrieves a `Page<>`.

.The parts of a search request
[source,java]
----
include::../../../../api/src/main/java/de/eitco/commons/query/language/api/SearchRequest.java[tag=members]
----

The `searchOptions` can be used to specify detailed behaviour.

=== Page Definition

The page definition contains information about the page of the result to retrieve. It can be created using its constructor and specifying, `offset`, `size` and `order` directly - but analogously to the fluent approach above:

.Two ways to specify a page
[source,java]
----
include::../../../../api/src/test/java/de/eitco/commons/query/language/api/test/sample/Fluent.java[tag=page-definition]
----

<1> creating a page definition directly by calling the constructor
<2> defining the same page definition using the fluent api

=== Filtering

Using the `filter` property one can specify a condition that every element of the result must meet.

The simplest condition is a boolean literal:

.Boolean literal
[source,java]
----
include::../../../../api/src/test/java/de/eitco/commons/query/language/api/test/sample/Fluent.java[tag=boolean-literal-low-level]
----
This will create the condition that always holds.

==== comparisons and values

In order to create more complex conditions the classes `ContextReference<>`, `Value<>` and `Equality<>` can be used:

.Boolean literal
[source,java]
----
include::../../../../api/src/test/java/de/eitco/commons/query/language/api/test/sample/Fluent.java[tag=comparison-low-level]
----

This would create the following sql `WHERE`-clause

[source,sql]
----
WHERE "my"."property" = 400
----

For other comparison operators the classes `GreaterThan`, `LessThan`, `LikeExpression`, `StartsWithExpression` and `Contains` are available.

==== boolean operators

Conditions can be linked by the boolean operators "and" and "or" using the classes `AndExpression` and `OrExpression`. The negation is provided by `NotExpression`.

.A complex query using the low level api
[source,java]
----
include::../../../../api/src/test/java/de/eitco/commons/query/language/api/test/sample/Fluent.java[tag=complex-low-level]
----

This would result in the following `WHERE`-clause

[source,sql]
----
WHERE
    ("my"."property" < 400 AND NOT 'my-value' = "other-property") OR
    (NOT "field" = 'value') OR
    ("my"."property" > 600 AND "field" = 'more')
----

So, given a `SearchService` one can use the low level api to query a result page as follows:


.Complete low level search example
[source,java]
----
include::../../../../api/src/test/java/de/eitco/commons/query/language/api/test/sample/Fluent.java[tag=search-low-level]
----

This will retrieve elements whose property `my.property` does not have the value `400`, ordered by the field `field`. The first 200 elements will not be returned and only the 400 following will (should they exist).