

=== Solr EQL Usage

If you want to use the Solr EQL visitor, there are two ways to do this. If you want to search in an existing Solr you can use 1). If you want to get a Solr query string you can use 2).

1) With _SolrSearchService_

[source,java]
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrFilterTest.java[tag=solr-createSolrEqlClient]
----

The first thing you will need is a _SolrClient_ (from SolrJ). You also need a _SolrSearchService_. The _SolrSearchService_ needs two parameters. The first parameter is the previously created _SolrClient_ and the second parameter is an optional _map_ of information about the current schema in the solr collection for the query. Finally, you will need an EQL Expression. In chapter xref:_solr_eql_expressions[Solr EQL Expressions] the individual Solr Expressions are presented. Whenever you create the queries above, you can create a _SearchRequest_ and put the variables in the instantiation. Moreover, you can add a _PageDefinition_. In this example we used _PageDefinition.oneElement()_.

[source,java]
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrFilterTest.java[tag=solr-createSolrSearchRequest]
----

2) With _<Expression>.get.accept_:

[source,java]
----
    eqlElement.get().accept(new ToSolrEqlElementVisitor(schema), null)
----

In this way you get the search string out of the EQL Expression. You can add the Visitor to the _accept_ method. This will return the result search string.

[#_solr_eql_expressions]
=== Solr EQL Expressions

.Calling *equal to*:

The input value must be matched exactly in the search result.

[source,java]
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrSearchServiceSqlTest.java[tag=solr-equalTo]
----
Returns:
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrSearchServiceSqlTest.java[tag=solr-equalTo-result]
----

.Calling *like*:

You can add a wildcard to the input value. In the EQL you can use two different wildcards for example _?_ for a single character or _*_ for multiple characters. The result is based on the wildcard you are defined in the input value.

[source,java]
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrSearchServiceSqlTest.java[tag=solr-like]
----
Returns:
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrSearchServiceSqlTest.java[tag=solr-like-result]
----

.Calling *contains*:

The input value must be somewhere in the search result. Also, you can find a string in an array list.

[source,java]
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrSearchServiceSqlTest.java[tag=solr-contains]
----
Returns:
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrSearchServiceSqlTest.java[tag=solr-contains-result]
----

.Calling *in*:

The input value can contain multiply entries (array). The result gets the results out of the input array based on the field.

[source,java]
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrSearchServiceSqlTest.java[tag=solr-in]
----
Returns:
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrSearchServiceSqlTest.java[tag=solr-in-result]
----

.Calling *and* or *or*:

Connect two Expression with _and_.

[source,java]
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrSearchServiceSqlTest.java[tag=solr-and]
----
Returns:
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrSearchServiceSqlTest.java[tag=solr-and-result]
----

.Calling *greater than*:

The result is bigger than the input value.

[source,java]
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrSearchServiceSqlTest.java[tag=solr-greaterThan]
----
Returns:
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrSearchServiceSqlTest.java[tag=solr-greaterThan-result]
----

.Calling *less than*:

The result is smaller than the input value.

[source,java]
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrSearchServiceSqlTest.java[tag=solr-lessThan]
----
Returns:
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrSearchServiceSqlTest.java[tag=solr-lessThan-result]
----

.Calling *between*:

The result is between two input values without the left outermost and right outermost result.

[source,java]
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrSearchServiceSqlTest.java[tag=solr-between]
----
Returns:
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrSearchServiceSqlTest.java[tag=solr-between-result]
----

.Calling *between inclusive*:

The result is between two input values with the left outermost and right outermost result.

[source,java]
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrSearchServiceSqlTest.java[tag=solr-betweenInclusive]
----
Returns:
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrSearchServiceSqlTest.java[tag=solr-betweenInclusive-result]
----

.Calling *between right inclusive*:

The result is between two input values with the right outermost and without the left outermost result.

[source,java]
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrSearchServiceSqlTest.java[tag=solr-betweenRightInclusive]
----
Returns:
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrSearchServiceSqlTest.java[tag=solr-betweenRightInclusive-result]
----

.Calling *between left inclusive*:

The result is between two input values with the left outermost and without the right outermost result.

[source,java]
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrSearchServiceSqlTest.java[tag=solr-betweenLeftInclusive]
----
Returns:
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrSearchServiceSqlTest.java[tag=solr-betweenLeftInclusive-result]
----

=== Solr Hit Score

In Solr you can create a filter query with a hit score. The hit score is calculated from the number of requests linked with *and* or *or*.

Example:

You have three entries in your Solr collection in the field "testfeld"

[cols="3", options="header"]
|===
|Entry |Field |Content
|1
|testfeld
|Arveo EQL Test
|2
|testfeld
|Arveo EQL 1
|3
|testfeld
|Arveo EQL 2
|===

If you now use the following query:

[source,java]
----
Eql.condition()
.contextReference("testfeld").contains().value("Arveo")
.or(Eql.condition().contextReference("testfeld").contains().value("EQL").holds())
.or(Eql.condition().contextReference("testfeld").contains().value("Test").holds())
.holds()
----

All three entries would be returned as a result. Entry 2 and 3 would have a hit score of *2.0* and the 1st entry would have a hit score of *3.0*.

If you are using the EQL QueryExtensions, a hit score can be specified that must be met for the result. In the example we defined a hit-score of 1.0 for the minimum.

.Set hit score:
[source,java]
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrFilterTest.java[tag=solr-hitScoreFilter]
----
Returns:
----
{!frange l=1.0}query($q)
----

=== Solr Highlighting

In Solr you can create a highlighting query extension. The highlighting will be added at the end of the query string.

.Set acl as solr filter:
[source,java]
----
List<QueryExtension> queryExtensions = new ArrayList<>();
queryExtensions.add(new SolrHighlightingQueryExtension(500));
SearchRequest searchRequest = new SearchRequest(PageDefinition.oneElement(), expression, solrSearchOptions, queryExtensions);
----
Returns:
[source,url-parameter]
----
&hl=true&hl.method=unified&hl.fragsize=500&hl.tag.pre=<em>&hl.tag.post=</em>
----

More detail information about the highlighting you can find at the following at this url https://solr.apache.org/guide/8_11/highlighting.html.

=== ACL filter extension

The ACL filter extension uses a plugin that extends Solr with ACL checking functionality. The plugin's
documentation can be found in the Access Control Service documentation.

The extension makes it possible to define a filter query based on a minimum ACL right the user must have to be able to
find the documents.

.Example filter query
[source,json]
----
{!aclright userId=111 aclAssignmentId=222 granted=3}
----

The extension is used as shown in the example below:

.Usage of the ACL filter extension
[source,java,indent=0]
----
include::../../../../solr/src/test/java/de/eitco/commons/query/language/solr/test/SolrFilterTest.java[tags=solr-aclFilter]
----